[package]
name = "schema_validator"
version = "0.1.0"
authors = ["Michael Sproul <michael@sigmaprime.io>"]
edition = "2018"

[dependencies]
jsonschema = { version = "0.3.1", default-features = false }
serde_json = "1.0.59"
