name: schema checks

on:
  push:
  pull_request:

jobs:
  check_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: make check
